# Generated by Django 5.1.5 on 2025-02-04 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaternalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gravida', models.IntegerField()),
                ('parity', models.IntegerField()),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField()),
                ('lmp', models.DateField()),
                ('edd', models.DateField()),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced')], max_length=50)),
                ('county', models.CharField(max_length=50)),
                ('subcounty', models.CharField(blank=True, max_length=50, null=True)),
                ('ward', models.CharField(blank=True, max_length=50, null=True)),
                ('town_village', models.CharField(blank=True, max_length=100, null=True)),
                ('physical_address', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone', models.CharField(max_length=15)),
                ('id_number', models.CharField(blank=True, max_length=20, null=True)),
                ('huduma_number', models.CharField(blank=True, max_length=20, null=True)),
                ('education_level', models.CharField(blank=True, max_length=50, null=True)),
                ('next_of_kin_name', models.CharField(max_length=100)),
                ('next_of_kin_relationship', models.CharField(max_length=50)),
                ('next_of_kin_phone', models.CharField(max_length=15)),
                ('surgical_operation', models.BooleanField(default=False)),
                ('diabetes', models.BooleanField(default=False)),
                ('hypertension', models.BooleanField(default=False)),
                ('blood_transfusion', models.BooleanField(default=False)),
                ('drug_allergy', models.BooleanField(default=False)),
                ('other_allergies', models.TextField(blank=True, null=True)),
                ('family_history_twins', models.BooleanField(default=False)),
                ('family_history_tb', models.BooleanField(default=False)),
            ],
        ),
    ]
