# Generated by Django 5.1.5 on 2025-02-20 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MamaCare', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospitaluser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='hospitaluser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='hospitaluser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='hospitaluser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='hospitaluser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='hospitaluser',
            name='username',
        ),
    ]
