# Generated by Django 5.1.7 on 2025-04-07 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MamaCare', '0002_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildWeightRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField()),
                ('weight_kg', models.FloatField()),
                ('recorded_on', models.DateField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MamaCare.childprofile')),
            ],
        ),
    ]
