# Generated by Django 5.1.7 on 2025-04-02 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MamaCare', '0002_convert_to_mother_id_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childprofile',
            name='mothers_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MamaCare.maternalprofile'),
        ),
    ]
