# Generated by Django 5.1.5 on 2025-03-06 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MamaCare', '0002_alter_hospitaluser_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mother',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('contact', models.CharField(max_length=20)),
                ('registered_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('completed', 'Completed'), ('missed', 'Missed')], max_length=20),
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('is_follow_up', models.BooleanField(default=True)),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='MamaCare.mother')),
            ],
        ),
        migrations.CreateModel(
            name='BirthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField()),
                ('delivery_type', models.CharField(choices=[('normal', 'Normal'), ('c-section', 'C-Section')], max_length=50)),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MamaCare.child')),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MamaCare.mother')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MamaCare.mother'),
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=255)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], max_length=20)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MamaCare.child')),
            ],
        ),
    ]
