# Generated by Django 5.1.7 on 2025-04-07 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MamaCare', '0003_childweightrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childweightrecord',
            name='recorded_on',
        ),
        migrations.AddField(
            model_name='childweightrecord',
            name='age_group',
            field=models.CharField(choices=[('0-1', '0-1 year'), ('1-2', '1-2 years'), ('2-3', '2-3 years'), ('3-4', '3-4 years'), ('4-5', '4-5 years')], default='0-1', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='childweightrecord',
            name='month',
            field=models.CharField(max_length=20),
        ),
    ]
