# Generated by Django 5.1.7 on 2025-04-03 12:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MamaCare', '0003_alter_childprofile_mothers_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Immunization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_type', models.CharField(choices=[('BCG', 'BCG'), ('OPV', 'Oral Polio Vaccine (OPV)'), ('IPV', 'Inactivated Polio Vaccine (IPV)'), ('PENTA', 'Pentavalent (DPT-HepB-Hib)'), ('PCV', 'Pneumococcal Conjugate Vaccine (PCV)'), ('ROTA', 'Rotavirus Vaccine'), ('MR', 'Measles-Rubella (MR)'), ('YF', 'Yellow Fever'), ('VIT_A', 'Vitamin A Supplementation'), ('DEWORM', 'Deworming')], max_length=10)),
                ('date_administered', models.DateField()),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('dose_number', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('dose_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=50, null=True)),
                ('administered_by', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('scar_checked', models.BooleanField(blank=True, null=True)),
                ('scar_present', models.BooleanField(blank=True, null=True)),
                ('date_repeated', models.DateField(blank=True, null=True)),
                ('vitamin_a_dose', models.CharField(blank=True, choices=[('100000IU', '100,000 IU (6 months)'), ('200000IU', '200,000 IU (12+ months)')], max_length=20, null=True)),
                ('deworming_medication', models.CharField(blank=True, default='Albendazole', max_length=50, null=True)),
                ('deworming_dosage', models.CharField(blank=True, choices=[('200mg', '200mg (1-2 years)'), ('400mg', '400mg (2+ years)')], max_length=50, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immunizations', to='MamaCare.childprofile')),
            ],
            options={
                'verbose_name': 'Immunization Record',
                'verbose_name_plural': 'Immunization Records',
                'ordering': ['date_administered'],
            },
        ),
        migrations.CreateModel(
            name='AdverseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_occurred', models.DateField()),
                ('description', models.TextField()),
                ('batch_number', models.CharField(blank=True, max_length=50, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('manufacture_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('action_taken', models.TextField(blank=True, null=True)),
                ('reported_to_authorities', models.BooleanField(default=False)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adverse_events', to='MamaCare.childprofile')),
                ('immunization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adverse_events', to='MamaCare.immunization')),
            ],
            options={
                'ordering': ['-date_occurred'],
            },
        ),
    ]
