# Generated by Django 5.1.7 on 2025-04-07 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MamaCare', '0004_remove_childweightrecord_recorded_on_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildHeightRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_cm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('month', models.CharField(max_length=20)),
                ('age_group', models.CharField(choices=[('0-1', '0-1 years'), ('1-2', '1-2 years'), ('2-3', '2-3 years'), ('3-4', '3-4 years'), ('4-5', '4-5 years')], max_length=20)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='height_records', to='MamaCare.childprofile')),
            ],
        ),
    ]
