# Generated by Django 5.1.5 on 2025-03-10 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MamaCare', '0004_remove_child_mother_remove_vaccinationrecord_child_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=255)),
                ('experience_years', models.IntegerField()),
                ('qualifications', models.TextField()),
                ('availability', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Consultant', 'Consultant')], default='Full-time', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
