# Generated by Django 5.1.7 on 2025-04-03 14:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MamaCare', '0004_immunization_adverseevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adverseevent',
            options={'ordering': ['-date_occurred'], 'verbose_name': 'Adverse Event Following Immunization', 'verbose_name_plural': 'Adverse Events Following Immunization'},
        ),
        migrations.AddField(
            model_name='adverseevent',
            name='reported_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adverseevent',
            name='vaccine_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='immunization',
            name='deworming_age_given',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='immunization',
            name='mr_dose_age',
            field=models.CharField(blank=True, choices=[('6m', '6 months'), ('9m', '9 months'), ('18m', '18 months')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='immunization',
            name='vitamin_a_age_given',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='immunization',
            name='yf_eligible',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adverseevent',
            name='date_occurred',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='ARTRegimen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('regimen', models.CharField(max_length=100)),
                ('current_dose', models.CharField(max_length=100)),
                ('last_viral_load', models.PositiveIntegerField(blank=True, null=True)),
                ('last_vl_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='art_regimens', to='MamaCare.childprofile')),
            ],
            options={
                'verbose_name': 'ART Regimen',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ARVProphylaxis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('regimen', models.CharField(default='AZT+NVP', max_length=100)),
                ('status', models.CharField(choices=[('continuing', 'Continuing'), ('stopped', 'Stopped (HIV+)'), ('completed', 'Completed')], max_length=20)),
                ('discontinuation_date', models.DateField(blank=True, null=True)),
                ('discontinuation_reason', models.TextField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arv_prophylaxis', to='MamaCare.childprofile')),
            ],
            options={
                'verbose_name': 'ARV Prophylaxis',
                'verbose_name_plural': 'ARV Prophylaxes',
            },
        ),
        migrations.CreateModel(
            name='CTXProphylaxis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('dose', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('discontinued', 'Discontinued'), ('completed', 'Completed')], max_length=20)),
                ('discontinuation_date', models.DateField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ctx_prophylaxis', to='MamaCare.childprofile')),
            ],
            options={
                'verbose_name': 'CTX Prophylaxis',
                'verbose_name_plural': 'CTX Prophylaxes',
            },
        ),
        migrations.CreateModel(
            name='HIVInfantTesting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('1st_pcr', '1st DNA PCR'), ('confirm_pcr', 'Confirmatory DNA PCR'), ('2nd_pcr', '2nd DNA PCR (6 months)'), ('3rd_pcr', '3rd DNA PCR (12 months)'), ('antibody_18m', 'Antibody test (18 months)'), ('antibody_24m', 'Antibody test (24 months)'), ('final_antibody', 'Final antibody test (6 weeks post-weaning)')], max_length=20)),
                ('sample_date', models.DateField()),
                ('result', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('pending', 'Pending'), ('indeterminate', 'Indeterminate')], max_length=20)),
                ('viral_load', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hiv_tests', to='MamaCare.childprofile')),
            ],
            options={
                'ordering': ['sample_date'],
            },
        ),
        migrations.CreateModel(
            name='InfantIPT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eligible', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('dose', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, choices=[('active', 'Active'), ('completed', 'Completed')], max_length=20, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipt_records', to='MamaCare.childprofile')),
            ],
            options={
                'verbose_name': 'Infant IPT',
                'verbose_name_plural': 'Infant IPTs',
            },
        ),
        migrations.CreateModel(
            name='MicronutrientPowder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(23)])),
                ('sachets_issued', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('date_issued', models.DateField()),
                ('next_visit_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mnps', to='MamaCare.childprofile')),
            ],
            options={
                'ordering': ['month'],
                'unique_together': {('child', 'month')},
            },
        ),
    ]
