# Generated by Django 5.1.7 on 2025-04-08 21:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MamaCare', '0005_childheightrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntenatalVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('gestation_weeks', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(40)])),
                ('bp_systolic', models.IntegerField(blank=True, null=True)),
                ('bp_diastolic', models.IntegerField(blank=True, null=True)),
                ('hb_level', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('fundal_height', models.IntegerField(blank=True, null=True)),
                ('fetal_presentation', models.CharField(blank=True, choices=[('C', 'Cephalic'), ('B', 'Breech'), ('O', 'Other')], max_length=1)),
                ('next_visit_date', models.DateField()),
                ('icd10_code', models.CharField(default='Z34.00', max_length=10)),
                ('cpt_code', models.CharField(default='59400', max_length=10)),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MamaCare.maternalprofile')),
            ],
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('HIV', 'HIV'), ('Syphilis', 'Syphilis'), ('Hepatitis B', 'Hepatitis B'), ('Hb', 'Hemoglobin'), ('Blood Group', 'Blood Group'), ('RBS', 'Random Blood Sugar')], max_length=20)),
                ('result', models.CharField(choices=[('R', 'Reactive'), ('NR', 'Non-Reactive'), ('INC', 'Inconclusive'), ('NT', 'Not Tested')], max_length=3)),
                ('test_date', models.DateField()),
                ('loinc_code', models.CharField(blank=True, max_length=10)),
                ('snomed_code', models.CharField(blank=True, max_length=20)),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MamaCare.maternalprofile')),
            ],
        ),
        migrations.CreateModel(
            name='WeightRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('record_date', models.DateField()),
                ('gestation_weeks', models.IntegerField()),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MamaCare.maternalprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
