# Generated by Django 5.1.5 on 2025-03-12 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MamaCare', '0005_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousPregnancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregnancy_order', models.IntegerField()),
                ('year', models.IntegerField()),
                ('anc_visits', models.IntegerField()),
                ('place_of_birth', models.CharField(max_length=255)),
                ('gestation_weeks', models.IntegerField()),
                ('labour_duration', models.CharField(max_length=50)),
                ('mode_of_delivery', models.CharField(max_length=50)),
                ('birth_weight', models.IntegerField()),
                ('sex', models.CharField(max_length=10)),
                ('outcome', models.CharField(max_length=50)),
                ('puerperium', models.CharField(max_length=50)),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MamaCare.maternalprofile')),
            ],
        ),
    ]
