# Generated by Django 5.1.7 on 2025-04-03 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MamaCare', '0005_alter_adverseevent_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childprofile',
            name='mothers_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='MamaCare.maternalprofile'),
        ),
    ]
