# Generated by Django 5.1.5 on 2025-03-16 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MamaCare', '0007_mother_child'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MamaCare.mother'),
        ),
    ]
