# Generated by Django 5.1.5 on 2025-03-16 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MamaCare', '0008_alter_child_mother'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('ANC, Childbirth and Postnatal Care', 'ANC, Childbirth and Postnatal Care'), ('Maternal Profile', 'Maternal Profile'), ('Medical & Surgical History', 'Medical & Surgical History'), ('Previous Pregnancy', 'Previous Pregnancy'), ('Antenatal Profile', 'Antenatal Profile'), ('Weight Monitoring Chart', 'Weight Monitoring Chart'), ('Clinical Notes', 'Clinical Notes'), ('Malaria Prophylaxis', 'Malaria Prophylaxis'), ('Maternal Serology Testing', 'Maternal Serology Testing'), ('Infant Feeding', 'Infant Feeding'), ('Danger Signs During Pregnancy', 'Danger Signs During Pregnancy'), ('Positioning for Breastfeeding', 'Positioning for Breastfeeding'), ('Child Health Monitoring', 'Child Health Monitoring'), ('Developmental Milestones', 'Developmental Milestones'), ('Growth Monitoring', 'Growth Monitoring'), ('Immunization', 'Immunization'), ('Vitamin A Supplementation', 'Vitamin A Supplementation'), ('Deworming', 'Deworming'), ('PMTCT of HIV/Syphilis/Hepatitis B', 'PMTCT of HIV/Syphilis/Hepatitis B'), ('Recommendations for Child Care', 'Recommendations for Child Care')], max_length=255)),
                ('details', models.TextField(blank=True)),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='MamaCare.child')),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='MamaCare.mother')),
            ],
        ),
    ]
