# Generated by Django 5.1.5 on 2025-03-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MamaCare', '0009_healthrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='mother',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mother',
            name='medical_history',
            field=models.TextField(blank=True),
        ),
    ]
