# Generated by Django 5.1.7 on 2025-03-24 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MamaCare', '0010_mother_date_of_birth_mother_medical_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mother',
            old_name='national_id',
            new_name='identification_number',
        ),
        migrations.RemoveField(
            model_name='mother',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='mother',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='child',
            name='health_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_health_record', to='MamaCare.healthrecord'),
        ),
        migrations.AlterField(
            model_name='child',
            name='mother',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MamaCare.mother'),
        ),
        migrations.AlterField(
            model_name='mother',
            name='medical_history',
            field=models.TextField(),
        ),
    ]
