# Generated by Django 5.1.7 on 2025-03-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MamaCare', '0011_rename_national_id_mother_identification_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotherChildRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
