# Generated by Django 5.1.7 on 2025-03-26 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MamaCare', '0012_motherchildrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalExamination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_pressure', models.CharField(help_text='e.g., 118/65 mmHg', max_length=10)),
                ('pulse_rate', models.PositiveIntegerField(help_text='Beats per minute')),
                ('cvs', models.TextField(blank=True, null=True)),
                ('respiratory_system', models.TextField(blank=True, null=True)),
                ('breasts', models.TextField(blank=True, null=True)),
                ('abdomen', models.TextField(blank=True, null=True)),
                ('genital_examination', models.TextField(blank=True, null=True)),
                ('discharge_or_ulcer', models.BooleanField(default=False, help_text='Check if present')),
                ('hemoglobin', models.FloatField(help_text='g/dl')),
                ('blood_group', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=3)),
                ('rhesus_factor', models.CharField(choices=[('TR+', 'TR+'), ('TR-', 'TR-')], max_length=5)),
                ('urinalysis', models.CharField(blank=True, max_length=50, null=True)),
                ('blood_rbs', models.FloatField(blank=True, help_text='Random blood sugar', null=True)),
                ('tb_screening_outcome', models.BooleanField(default=False, help_text='True = Positive, False = Negative')),
                ('ipt_given_date', models.DateField(blank=True, null=True)),
                ('ipt_next_visit', models.DateField(blank=True, null=True)),
                ('scan_first_date', models.DateField(blank=True, help_text='Before 24 weeks', null=True)),
                ('scan_second_date', models.DateField(blank=True, help_text='Third trimester', null=True)),
                ('hiv_status', models.CharField(choices=[('Reactive', 'Reactive'), ('Non-Reactive', 'Non-Reactive'), ('Not Tested', 'Not Tested')], default='Not Tested', max_length=20)),
                ('syphilis_status', models.CharField(choices=[('Reactive', 'Reactive'), ('Non-Reactive', 'Non-Reactive'), ('Not Tested', 'Not Tested')], default='Not Tested', max_length=20)),
                ('hepatitis_b_status', models.CharField(choices=[('Reactive', 'Reactive'), ('Non-Reactive', 'Non-Reactive'), ('Not Tested', 'Not Tested')], default='Not Tested', max_length=20)),
                ('couple_testing_done', models.BooleanField(default=False)),
                ('partner_hiv_status', models.CharField(choices=[('Reactive', 'Reactive'), ('Non-Reactive', 'Non-Reactive'), ('Not Tested', 'Not Tested')], default='Not Tested', max_length=20)),
            ],
        ),
    ]
