# Generated by Django 5.1.7 on 2025-03-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MamaCare', '0013_physicalexamination'),
    ]

    operations = [
        migrations.CreateModel(
            name='PregnancyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('urine', models.CharField(blank=True, max_length=10, null=True)),
                ('muac', models.PositiveIntegerField(help_text='Mid Upper Arm Circumference (cm)')),
                ('blood_pressure', models.CharField(help_text='e.g., 118/65 mmHg', max_length=10)),
                ('hb', models.FloatField(help_text='Hemoglobin level (g/dl)')),
                ('pallor', models.CharField(blank=True, max_length=20, null=True)),
                ('gestation_weeks', models.PositiveIntegerField()),
                ('fundal_height', models.CharField(blank=True, max_length=10, null=True)),
                ('presentation', models.CharField(blank=True, max_length=10, null=True)),
                ('lie', models.CharField(blank=True, max_length=10, null=True)),
                ('fetal_heart_rate', models.PositiveIntegerField(help_text='Beats per minute')),
                ('fetal_movement', models.BooleanField(default=True)),
                ('mental_health_status', models.CharField(blank=True, max_length=100, null=True)),
                ('next_visit', models.DateField()),
            ],
        ),
    ]
