# Generated by Django 5.1.7 on 2025-03-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MamaCare', '0014_pregnancyrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('gestation_at_birth', models.PositiveIntegerField(blank=True, null=True)),
                ('birth_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('birth_length', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('birth_order', models.PositiveIntegerField(blank=True, null=True)),
                ('date_first_seen', models.DateField()),
                ('place_of_birth', models.CharField(choices=[('Home', 'Home'), ('Hospital', 'Hospital'), ('Other', 'Other')], max_length=20)),
                ('health_facility_name', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_notification_no', models.CharField(blank=True, max_length=20, null=True)),
                ('immunization_registration_no', models.CharField(blank=True, max_length=20, null=True)),
                ('child_welfare_clinic_no', models.CharField(blank=True, max_length=20, null=True)),
                ('master_facility_code', models.CharField(blank=True, max_length=20, null=True)),
                ('birth_certificate_no', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_registration', models.DateField(blank=True, null=True)),
                ('place_of_registration', models.CharField(blank=True, max_length=100, null=True)),
                ('fathers_name', models.CharField(blank=True, max_length=100, null=True)),
                ('fathers_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('mothers_name', models.CharField(max_length=100)),
                ('mothers_phone', models.CharField(max_length=20)),
                ('guardian_name', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('residence', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('division', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_county', models.CharField(blank=True, max_length=100, null=True)),
                ('town', models.CharField(blank=True, max_length=100, null=True)),
                ('estate_village', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_address', models.CharField(blank=True, max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
