# Generated by Django 5.1.7 on 2025-03-27 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MamaCare', '0016_maternalprofile_guardian_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maternalprofile',
            old_name='id_number',
            new_name='identification_number',
        ),
    ]
